### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by mamantoha** [jessedoyle/xss_test#1]
Hi @jessedoyle .

I found this repository through https://shards.info/

<img width="723" alt="Screenshot_20200528_122713" src="https://user-images.githubusercontent.com/61285/83124254-a040b300-a0de-11ea-890c-bc0be596aef4.png">
 
Already fixed :tada:

**Comment by jessedoyle** [comment]
Great! It's really easy to miss, so I'm glad I was able to help!
